cart/urls.py
from django.urls import path
from cart.views import *

app_name = "cart"

urlpatterns = [
    path('', cart_summary, name='cart_summary'),
    path('add/', cart_add, name='card_add'),
    path('delete/', cart_delete, name='cart_delete'),
    path('update/', cart_update, name='cart_update'),
]

e_commerce_django/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from e_commerce_django.views import *
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('payment/', include('payment.urls')),
    path('', redirect_to_home),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from payment.views import *

app_name = 'payment'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('complete_order/', complete_order, name='complete_order'),
    path('my_orders/', my_orders, name='my_orders'),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = "store"

urlpatterns = [
    path('', store, name='store'),
    path('product_info/<slug:slug>/', product_info, name='product_info'),
    path('search/<slug:slug>/', search, name='search'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404
from store.models import Product
from account.models import UserCart
from .cart import Cart
from django.http import JsonResponse

def cart_summary(request):
    cart = Cart(request)

    if len(cart) > 0:
        return render(request, 'cart/cart_summary.html', context={'title': 'Product Destination | Cart', 'cart': cart})

    return render(request, 'empty_cart.html', context={'title': 'Product Destination | Cart'})

def cart_add(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        quantity = int(request.POST.get('quantity'))

        product = get_object_or_404(Product, id=product_id)
        cart.add(product, quantity)

        UserCart.objects.filter(username=request.user.username).update(user_cart=request.session['cart'], total=request.session['total'])

        return JsonResponse({'cart_qty': len(cart)})

def cart_delete(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))

        product = get_object_or_404(Product, id=product_id)
        cart.delete(product)

        UserCart.objects.filter(username=request.user.username).update(user_cart=request.session['cart'], total=request.session['total'])

        return JsonResponse({'cart_qty': len(cart), 'cart_total': cart.total})

def cart_update(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        quantity = int(request.POST.get('quantity'))

        product = get_object_or_404(Product, id=product_id)
        cart.update(product, quantity)

        UserCart.objects.filter(username=request.user.username).update(user_cart=request.session['cart'], total=request.session['total'])

        return JsonResponse({'cart_qty': len(cart), 'cart_total': cart.total})

templates/cart/cart_summary.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/cart_summary.css' %}">
{% endblock %}

{% block body %}
    <div class="main mt-4 ms-4 mb-5">
        <h3 class="text-capitalize">Your Cart</h3>
        {% for item in cart %}
            {% with product=item.product %}
                <div class="product p-3 mb-4 rounded-corner" id="{{ product.id }}">
                    <div class="left">
                        <img class="product_img" src="{{ product.image.url }}" alt="Image not found">
                    </div>
                    <div class="right">
                        <a href="{% url 'store:product_info' product.slug %}" class="title h2 text-capitalize">{{ product.title | replaceChar:"-, " }}</a>

                        <div class="price_details mt-5">
                            <p class="fw-normal text-capitalize text-white">Price</p>
                            <p class="price lead fw-bold text-white">{{ product.price | indianPrice }}</p>
                        </div>

                        <div class="price_details" style="margin-top: 0">
                            <div>
                                <p class="fw-normal text-white">Quantity</p>
                                <select class="quantity form-select-sm rounded-corner text-white p-2 {{ product.id }}" data-index="{{ product.id }}">
                                    <option value="{{ item.qty }}" selected disabled hidden>{{ item.qty }}</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                </select>
                            </div>
                            <button class="delete-btn btn rounded-corner text-capitalize text-black" value="{{ product.id }}">Delete</button>
                        </div>
                    </div>
                </div>
            {% endwith %}
        {% endfor %}

        <div class="final_price mt-4 p-3 justify-content-end align-items-center" style="display: flex">
            <h3 class="text-capitalize me-5">Total price: {{ cart.total | indianPrice }}</h3>
            <a href="{% url 'payment:checkout' %}" class="buy-btn btn rounded-corner text-capitalize text-black">
                Buy Now
            </a>
        </div>

    </div>
{% endblock %}

{% block script %}
    <script>
        $(document).on('click', '.delete-btn', function (event) {
            event.preventDefault();
            let product_id = $(this).val();

            $.ajax({
                type: "POST",
                url: "{% url 'cart:cart_delete' %}",
                data: {
                    product_id: product_id,
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: 'post'
                },
                success: function (json) {
                    if (json.cart_qty === 0)
                    {
                        window.location.href = "{% url 'cart:cart_summary' %}";
                        return
                    }

                    let indianPrice = json.cart_total.toLocaleString('en-IN', {
                        maximumFractionDigits: 2,
                        style: 'currency',
                        currency: 'INR',
                    });

                    $('.cart_qty').text(json.cart_qty);
                    $(`#${product_id}`).remove();
                    $('.final_price h3').text(`Total price: ${indianPrice}`);
                },
                error: function (xhr, msg, err) {
                    console.log(err);
                }
            });
        });

        $(document).on('change', '.quantity', function (event) {
            event.preventDefault();
            let product_id = $(this).attr('data-index');

            $.ajax({
                type: "POST",
                url: "{% url 'cart:cart_update' %}",
                data: {
                    product_id: product_id,
                    quantity: $(`.${product_id} option:selected`).text(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: 'post'
                },
                success: function (json) {
                    if (json.cart_qty === 0)
                    {
                        window.location.href = "{% url 'cart:cart_summary' %}";
                        return
                    }

                    let indianPrice = json.cart_total.toLocaleString('en-IN', {
                        maximumFractionDigits: 2,
                        style: 'currency',
                        currency: 'INR',
                    });

                    $('.cart_qty').text(json.cart_qty);
                    $('.final_price h3').text(`Total price: ${indianPrice}`);
                },
                error: function (xhr, msg, err) {
                    console.log(err);
                }
            });
        });
    </script>
{% endblock %}