account/urls.py
from django.urls import path, reverse_lazy
from account.views import *
from django.contrib.auth import views

app_name = "account"

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('logout/', user_logout, name='logout'),
    path('email_verification/<str:uidb64>/<str:token>', email_verification, name='email_verification'),
    path('email_verification_sent/', email_verification_sent, name='email_verification_sent'),
    path('email_verification_success/', email_verification_success, name='email_verification_success'),
    path('profile/', profile, name='profile'),
    path('delete/', delete_account, name='delete'),
    path('reset_password/', views.PasswordResetView.as_view(template_name='account/password/reset_password.html', success_url=reverse_lazy('account:password_reset_done'), email_template_name='account/password/reset_password_email.html'), name='reset_password'),
    path('reset_password_sent/', views.PasswordResetDoneView.as_view(template_name='account/password/reset_password_sent.html'), name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/', views.PasswordResetConfirmView.as_view(template_name='account/password/reset.html', success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),
    path('reset_password_complete/', views.PasswordResetCompleteView.as_view(template_name='account/password/reset_password_complete.html'), name='password_reset_complete'),
    path('manage_shipping/', manage_shipping, name='manage_shipping'),
]

cart/urls.py
from django.urls import path
from cart.views import *

app_name = "cart"

urlpatterns = [
    path('', cart_summary, name='cart_summary'),
    path('add/', cart_add, name='card_add'),
    path('delete/', cart_delete, name='cart_delete'),
    path('update/', cart_update, name='cart_update'),
]

e_commerce_django/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from e_commerce_django.views import *
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('payment/', include('payment.urls')),
    path('', redirect_to_home),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from payment.views import *

app_name = 'payment'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('complete_order/', complete_order, name='complete_order'),
    path('my_orders/', my_orders, name='my_orders'),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = "store"

urlpatterns = [
    path('', store, name='store'),
    path('product_info/<slug:slug>/', product_info, name='product_info'),
    path('search/<slug:slug>/', search, name='search'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        {% if title %}
            <title>{{ title }}</title>
        {% endif %}

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" href="{% static 'img/brand_logo_favicon.jpeg' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        {% block head %}

        {% endblock %}

        <link rel="stylesheet" href="https://bootswatch.com/5/cyborg/bootstrap.min.css">
        <script src="https://kit.fontawesome.com/f6a1fc2dc1.js" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>

        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-2 text-uppercase">
            <div class="container-fluid">
                <a class="hover-underline-animation navbar-brand" href="{% url 'store:store' %}">
                    <img src="{% static 'img/brand_logo.jpeg' %}" alt="Logo" width="50" height="44" class="d-inline-block align-text-center">
                    Product Destination
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropend">
                            <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categories
                            </a>
                            <ul class="dropdown-menu rounded-corner">
                                <li><a class="dropdown-item" href="{% url 'store:store' %}">All</a></li>
                                {% for category in all_categories %}
                                    <li><a class="dropdown-item" href="{% url 'store:search' category.slug %}">{{ category.name | title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        {% if not request.user.is_authenticated %}
                            <li class="nav-item me-3">
                                <a class=" hover-underline-animation nav-link active" href="{% url 'account:signup' %}">Sign Up</a>
                            </li>
                            <li class="nav-item me-3">
                                <a class="hover-underline-animation nav-link active" href="{% url 'account:signin' %}">Sign In</a>
                            </li>
                        {% else %}
                            <li class="nav-item me-3">
                                <a class="hover-underline-animation nav-link active" href="{% url 'payment:my_orders' %}">My Orders</a>
                            </li>
                            <li class="nav-item me-3">
                                <a class="hover-underline-animation nav-link active" href="{% url 'account:profile' %}">Profile</a>
                            </li>
                            <li class="nav-item me-3">
                                <a class="hover-underline-animation nav-link active" href="{% url 'account:logout' %}">Logout</a>
                            </li>
                        {% endif %}
                        <li class="nav-item me-3">
                            <a class="hover-underline-animation nav-link active" href="{% url 'cart:cart_summary' %}">
                                <i class="fas fa-shopping-cart"></i>
                                <span class="cart_qty">
                                    {% with qty=cart|length %}
                                        {% if qty > 0 %}
                                            {{ qty }}
                                        {% else %}
                                            0
                                        {% endif %}
                                    {% endwith %}
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block body %}

        {% endblock %}

        {% block script %}

        {% endblock %}
    </body>
</html>

templates/empty_cart.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/empty_cart.css' %}">
{% endblock %}

{% block body %}
    <div class="emoji_card">
        <div class="emoji-sad mb-4">
            <div class="face">
                <div class="eyebrow-left"></div>
                <div class="eyebrow-right"></div>
                <div class="eye-left"></div>
                <div class="eye-right"></div>
                <div class="mouth-sad"></div>
            </div>
        </div>
        
        {% if request.path == '/cart/' %}
            <p class="lead text-white font-weight-bolder">Oops! Looks like the cart is empty</p>
        {% else %}
            <p class="lead text-white font-weight-bolder">Oops! Looks like you have no orders</p>
        {% endif %}
        <p class="lead text-white font-weight-bolder">Make me happy by shopping something</p>

        <a href="{% url 'store:store' %}" class="btn text-uppercase text-black">
            Go Shopping
        </a>
    </div>
{% endblock %}

{% block script %}
    <script>
        $('.btn').hover(function () {
            $('.mouth-sad').addClass('mouth-happy').removeClass('mouth-sad');
        }, function () {
            $('.mouth-happy').addClass('mouth-sad').removeClass('mouth-happy');
        });
    </script>
{% endblock %}