cart/urls.py
from django.urls import path
from cart.views import *

app_name = "cart"

urlpatterns = [
    path('', cart_summary, name='cart_summary'),
    path('add/', cart_add, name='card_add'),
    path('delete/', cart_delete, name='cart_delete'),
    path('update/', cart_update, name='cart_update'),
]

e_commerce_django/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from e_commerce_django.views import *
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('payment/', include('payment.urls')),
    path('', redirect_to_home),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import *

app_name = "store"

urlpatterns = [
    path('', store, name='store'),
    path('product_info/<slug:slug>/', product_info, name='product_info'),
    path('search/<slug:slug>/', search, name='search'),
]

store/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    title = models.CharField(max_length=150)
    brand = models.CharField(max_length=150, default="non-branded")
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=150, unique=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='images/')

    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = 'products'

    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import render, get_object_or_404
from store.models import *

def categories(request):
    all_categories = Category.objects.all()
    return {'all_categories': all_categories}

def products(request):
    all_products = Product.objects.all()
    return {'all_products': all_products}

def store(request):
    return render(request, 'store/store.html', context={'title': 'Product Destination | Store', 'category': None})

def product_info(request, slug):
    product = get_object_or_404(Product, slug=slug)
    return render(request, 'store/product_info.html', context={'title': product.title.replace('-', ' ').title(), 'product': product})

def search(request, slug):
    category = get_object_or_404(Category, slug=slug)
    return render(request, 'store/store.html', context={'title': 'Product Destination | Store', 'category': category})

templates/store/product_info.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/product_info.css' %}">
{% endblock %}

{% block body %}
    <div class="row justify-content-between mt-3">
        <div class="col-md-5">
            <img class="product_img" src="{{ product.image.url }}" alt="" width="100%" height="100%">
        </div>

        <div class="col-md-5">
            <h1 class="display-5 text-capitalize">{{ product.title | replaceChar:"-, " }}</h1>
            <h5 class="text-capitalize">{{ product.brand | replaceChar:"-, " }}</h5>

            <p class="lead mt-5 text-white">
                {{ product.description }}
            </p>

            <div class="price_details rounded-corner">
                <p class="fw-normal text-white font-weight-bolder">Price</p>
                <p class="price lead fw-bold text-white">{{ product.price | indianPrice }}</p>
            </div>

            <div class="price_details rounded-corner" style="margin-top: 0">
                <div>
                    <p class="fw-normal text-white">Quantity</p>
                    <select class="quantity form-select-sm rounded-corner p-2" style="">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                    </select>
                </div>

                <button class="add-btn btn rounded-corner text-uppercase text-black p-3" id="liveToastBtn" value="{{ product.id }}" style="background-color: #FFCE00">
                    Add to cart
                </button>

                <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
                    <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true" data-bs-delay="2000">
                        <div class="toast-header">
                            <strong class="me-auto">Product Destination</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                        <div class="toast-body text-capitalize">
                            {{ product.title | replaceChar:"-, " }} added to cart.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        document.getElementById("liveToastBtn").onclick = function() {
            $('.toast').toast('show');
        };

        $(document).on('click', '.add-btn', function(event) {
            event.preventDefault();

            $.ajax({
                type: 'POST',
                url: "{% url 'cart:card_add' %}",
                data: {
                    product_id: $('.add-btn').val(),
                    quantity: $('.quantity option:selected').text(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: 'post'
                },
                success: function (json) {
                    $('.cart_qty').text(json.cart_qty);
                },
                error: function (xhr, msg, err) {
                    console.log(err)
                }
            });
        });
    </script>
{% endblock %}

templates/store/store.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/store.css' %}">
{% endblock %}

{% block body %}
    <div class="all_products mb-5">
        {% for product in all_products %}
            {% if category and product.category != category %}
            {% else %}
                <div class="product_card">
                    <div class="imgBox">
                        <img class="product_img" src="{{ product.image.url }}" alt="Image not found!">
                    </div>
                    <div class="contentBox">
                        <h3>
                            {% if product.brand != "non-branded" %}
                                {{ product.brand | replaceChar:"-, " }}
                            {% endif %}
                            {{ product.title | replaceChar:"-, " }}
                        </h3>
                        <h2 class="price">{{ product.price | indianPrice }}</h2>
                        <a href="{% url 'store:product_info' product.slug %}" class="buy">View more</a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}