cart/urls.py
from django.urls import path
from cart.views import *

app_name = "cart"

urlpatterns = [
    path('', cart_summary, name='cart_summary'),
    path('add/', cart_add, name='card_add'),
    path('delete/', cart_delete, name='cart_delete'),
    path('update/', cart_update, name='cart_update'),
]

e_commerce_django/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from e_commerce_django.views import *
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('payment/', include('payment.urls')),
    path('', redirect_to_home),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from payment.views import *

app_name = 'payment'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('complete_order/', complete_order, name='complete_order'),
    path('my_orders/', my_orders, name='my_orders'),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = "store"

urlpatterns = [
    path('', store, name='store'),
    path('product_info/<slug:slug>/', product_info, name='product_info'),
    path('search/<slug:slug>/', search, name='search'),
]

payment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, ValidationError
from store.models import Product
from datetime import datetime

def only_int(value):
    try:
        value = int(value)
        return value
    except:
        raise ValidationError('Zip code must contain only numbers')

class ShippingAddress(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    full_name = models.CharField(max_length=150)
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=6, validators=[
        MinLengthValidator(4),
        only_int,
    ])

    class Meta:
        verbose_name_plural = 'Shipping Address'

    def __str__(self):
        return self.user.username

    def get_full_address(self):
        return self.address1 + "," + self.address2 + "," + self.city + "," + self.state + "," + self.zipcode

class Order(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    full_name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    shipping_address = models.TextField(max_length=10000)
    amount_total = models.DecimalField(max_digits=8, decimal_places=2)
    date_ordered = models.DateTimeField(default=datetime.now(), editable=False)

    def __str__(self):
        return "Order " + str(self.id)

class OrderItem(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)

    quantity = models.PositiveBigIntegerField(default=1)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return "Order Item " + str(self.id)

payment/forms.py
from django import forms
from payment.models import ShippingAddress

class ShippingForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ['full_name', 'address1', 'address2', 'city', 'state', 'zipcode']
        exclude = ['user',]

    def __init__(self, *args, **kwargs):
        super(ShippingForm, self).__init__(*args, **kwargs)

        self.fields['full_name'].widget.attrs['placeholder'] = 'Full name'
        self.fields['address1'].widget.attrs['placeholder'] = 'Address1'
        self.fields['address2'].widget.attrs['placeholder'] = 'Address2'
        self.fields['city'].widget.attrs['placeholder'] = 'City'
        self.fields['state'].widget.attrs['placeholder'] = 'State'
        self.fields['zipcode'].widget.attrs['placeholder'] = 'Zip Code'

payment/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from payment.models import *
from account.models import *
from django.contrib import messages

@login_required(login_url='account:signin')
def checkout(request):
    shipping = ShippingAddress.objects.filter(user=request.user.id)
    if not shipping:
        messages.error(request, 'Please update shipping details to checkout!')
        return redirect('account:profile')

    return render(request, 'payment/checkout.html', context={'title': 'Checkout'})

@login_required(login_url='account:signin')
def complete_order(request):
    if request.POST.get('action') == 'post':
        shipping = ShippingAddress.objects.get(user=request.user.id)

        order = Order.objects.create(
            user = request.user,
            full_name = shipping.full_name,
            email = request.user.email,
            shipping_address = shipping.get_full_address(),
            amount_total = request.session['total'],
        )

        for item in request.session['cart']:
            order_item = OrderItem.objects.create(
                user = request.user,
                order = order,
                product = Product.objects.get(id=item),
                quantity = request.session['cart'][item]['qty'],
                price = request.session['cart'][item]['price'],
            )

        messages.success(request, f'Order #{order.id} placed successfully')
        user_cart = UserCart.objects.filter(username=request.user.username).update(user_cart={}, total=0.0)
        request.session['cart'] = {}
        request.session['total'] = 0.0
        return redirect('payment:my_orders')

    return redirect('payment:checkout')

@login_required(login_url='account:signin')
def my_orders(request):
    orders = Order.objects.filter(user=request.user)

    if len(orders) == 0:
        return render(request, 'empty_cart.html', context={'title': 'My Orders'})
    
    order_items = OrderItem.objects.filter(order__in=orders)
    return render(request, 'payment/my_orders.html', context={'title': 'My Orders', 'orders': orders, 'order_items': order_items})

templates/payment/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/cart_summary.css' %}">
    <link rel="stylesheet" href="{% static 'css/checkout.css' %}">
{% endblock %}

{% block body %}
    <canvas id="canvas" width="250" height="250"></canvas>

    <div class="main mt-4 ms-4 mb-5">
        <h3 class="text-capitalize">Your Cart</h3>
        {% for item in cart %}
            {% with product=item.product %}
                <div class="product p-3 mb-4 rounded-corner" id="{{ product.id }}">
                    <div class="left">
                        <img class="product_img" src="{{ product.image.url }}" alt="Image not found">
                    </div>
                    <div class="right">
                        <p class="title h2 text-capitalize">{{ product.title | replaceChar:"-, " }}</p>

                        <div class="price_details mt-5">
                            <p class="fw-normal text-capitalize text-white">Price</p>
                            <p class="price lead fw-bold text-white">{{ product.price | indianPrice }}</p>
                        </div>

                        <div class="price_details" style="margin-top: 0">
                            <div>
                                <p class="fw-normal text-white">Quantity: {{ item.qty }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endwith %}
        {% endfor %}

        <div class="final_price mt-4 p-3 justify-content-end align-items-center" style="display: flex">
            <h3 class="text-capitalize me-5">Total price: {{ cart.total | indianPrice }}</h3>
            <a href="{% url 'cart:cart_summary' %}" class="buy-btn btn rounded-corner text-capitalize text-black me-3">
                Go Back
            </a>
{#            <button class="complete-btn btn rounded-corner text-capitalize text-black">#}
{#                Confirm order#}
{#            </button>#}
            <div id="paypal-button-container"></div>
            <span class="text-monospace">*Checkout is done in USD</span>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $('nav').css('opacity', '0');
        $('.main').css('opacity', '0');

        var canvasLoader = function ()
        {
            var self = this;
            window.requestAnimFrame = function ()
            {
                return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function (a)
                {
                    window.setTimeout(a, 1E3 / 60)
                }
            }();

            self.init = function ()
            {
                self.canvas = document.getElementById('canvas');
                self.ctx = self.canvas.getContext('2d');
                self.ctx.lineWidth = .5;
                self.ctx.strokeStyle = 'rgba(255,255,255,1)';
                self.count = 75;
                self.rotation = 270 * (Math.PI / 180);
                self.speed = 6;
                self.canvasLoop();
            };

            self.updateLoader = function ()
            {
                self.rotation += self.speed / 100;
            };

            self.renderLoader = function ()
            {
                self.ctx.save();
                self.ctx.globalCompositeOperation = 'source-over';
                self.ctx.translate(125, 125);
                self.ctx.rotate(self.rotation);
                var i = self.count;
                while (i--)
                {
                    self.ctx.beginPath();
                    self.ctx.arc(0, 0, i + (Math.random() * 35), Math.random(), Math.PI / 3 + (Math.random() / 12), false);
                    self.ctx.stroke();
                }
                self.ctx.restore();
            };

            self.canvasLoop = function ()
            {
                requestAnimFrame(self.canvasLoop, self.canvas);
                self.ctx.globalCompositeOperation = 'destination-out';
                self.ctx.fillStyle = 'rgba(255,255,255,0.03)';
                self.ctx.fillRect(0, 0, 250, 250);
                self.updateLoader();
                self.renderLoader();
            };

        };

        var loader = new canvasLoader();
        loader.init();
    </script>

    <script src="https://www.paypal.com/sdk/js?client-id=AU-El3DtPfgZpGFJXbBBHBqqslxqXnOrwRuYDOxTi8GJBpKsbY5JLU72fMmdmiJSF9AY18hn_JHVahIi&currency=USD&intent=capture&enable-funding=venmo" data-sdk-integration-source="integrationbuilder"></script>

    <script>
        let myHeaders = new Headers();
        myHeaders.append("apikey", "jK1qvEW3NZDPUjdSDohvQm1aehrLJS6w");

        let requestOptions = {
            method: 'GET',
            redirect: 'follow',
            headers: myHeaders
        };

        var price;

        fetch('https://api.apilayer.com/exchangerates_data/convert?to=USD&from=INR&amount={{ cart.total }}', requestOptions)
            .then(response => {
                console.log('hello');
                return response.json();
            })
            .then(result => {
                    const paypalButtonsComponent = paypal.Buttons({
                        // optional styling for buttons
                        // https://developer.paypal.com/docs/checkout/standard/customize/buttons-style-guide/
                        style: {
                            color: "black",
                            shape: "rect",
                            height: 40,
                            layout: "horizontal",
                            tagline: false,
                            label: "checkout",
                        },

                        // set up the transaction
                        createOrder: (data, actions) =>
                        {
                            // pass in any options from the v2 orders create call:
                            // https://developer.paypal.com/api/orders/v2/#orders-create-request-body
                            price = result.result.toFixed(2).toString();
                            const createOrderPayload = {
                                purchase_units: [
                                    {
                                        amount: {
                                            value: price,
                                        }
                                    }
                                ]
                            };

                            return actions.order.create(createOrderPayload);
                        },

                        // finalize the transaction
                        onApprove: (data, actions) =>
                        {
                            const captureOrderHandler = (details) =>
                            {
                                const payerName = details.payer.name.given_name;

                                $.ajax({
                                    type: 'POST',
                                    url: "{% url 'payment:complete_order' %}",
                                    data: {
                                        csrfmiddlewaretoken: "{{ csrf_token }}",
                                        action: 'post',
                                    },
                                    success: function (json) {
                                        console.log('Success');
                                        window.location.href = '{% url 'payment:my_orders' %}';
                                    },
                                    error: function (xhr, msg, err) {
                                        console.log(err);
                                    }
                                });
                            };

                            return actions.order.capture().then(captureOrderHandler);
                        },

                        // handle unrecoverable errors
                        onError: (err) =>
                        {
                            console.error('An error prevented the buyer from checking out with PayPal');
                        }
                    });

                    paypalButtonsComponent
                        .render("#paypal-button-container")
                        .then(
                            $('nav').css('opacity', '1'),
                            $('.main').css('opacity', '1'),
                            $('#canvas').css('display', 'none')
                        )
                        .catch((err) =>
                        {
                            console.error('PayPal Buttons failed to render');
                        });
                }
            )
    </script>
{% endblock %}

templates/payment/my_orders.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/cart_summary.css' %}">
{% endblock %}

{% block body %}
    {% for order in orders %}
        <a class="btn text-black m-3 justify-content-center" data-bs-toggle="collapse" href="#{{ order.id }}" role="button" aria-expanded="false" aria-controls="collapseExample" style="width: 40%">
            Order #{{ order.id }} &nbsp; Date Ordered: {{ order.date_ordered }}
        </a>

        {% for item in order_items %}
            {% if item.order == order %}
                <div class="collapse" id="{{ order.id }}">
                    <div class="product p-3 mb-4 rounded-corner">
                        <div class="left">
                            <img class="product_img" src="{{ item.product.image.url }}" alt="Image not found">
                        </div>
                        <div class="right">
                            <a href="{% url 'store:product_info' item.product.slug %}" class="title h2 text-capitalize">{{ item.product.title | replaceChar:"-, " }}</a>

                            <div class="price_details mt-5">
                                <p class="fw-normal text-capitalize text-white">Price</p>
                                <p class="price lead fw-bold text-white">{{ item.product.price | indianPrice }}</p>
                            </div>

                            <div class="price_details" style="margin-top: 0">
                                <div>
                                    <p class="fw-normal text-white">Quantity: {{ item.quantity }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endblock %}